Repository dod-advana/gamechanger-ml, pull requests merged in 2022-03, with the labels that each got.

#100 task/UOT-130520 - more fixes finetuning/training data
  gamechangerml/api/fastapi/routers/controls.py
  gamechangerml/data/.gitignore
  gamechangerml/scripts/make_training_data.py
  gamechangerml/scripts/update_eval_data.py
  gamechangerml/src/model_testing/metrics.py
  gamechangerml/src/model_testing/validation_data.py
  gamechangerml/src/search/sent_transformer/finetune.py
  gamechangerml/src/search/sent_transformer/model.py
  gamechangerml/src/utilities/test_utils.py
  gamechangerml/train/pipeline.py
Labels: v1.3.0

#101 Changes from testing out BERT models
  .gitignore
  gamechangerml/api/.dockerignore
  gamechangerml/api/fastapi/routers/search.py
  gamechangerml/configs/config.py
  gamechangerml/scripts/make_training_data.py
  gamechangerml/src/model_testing/queries.csv
  gamechangerml/src/model_testing/search_gen.py
  gamechangerml/src/search/sent_transformer/model.py
  gamechangerml/src/text_handling/corpus.py
  gamechangerml/src/text_handling/process.py
Labels: v1.3.0

#106 Hotfix/corpus bug
  gamechangerml/__init__.py
  gamechangerml/api/.env
  gamechangerml/api/fastapi/cpu.mlapp.Dockerfile
  gamechangerml/api/fastapi/gpu.mlapp.Dockerfile
  gamechangerml/scripts/make_training_data.py
  gamechangerml/setup_env.sh
Labels: v1.4.0

#104 Task/UOT-132221
  gamechangerml/api/fastapi/routers/controls.py
  gamechangerml/api/utils/processmanager.py
  gamechangerml/api/utils/status_updater.py
  gamechangerml/src/search/sent_transformer/finetune.py
  gamechangerml/src/search/sent_transformer/model.py
  gamechangerml/src/text_handling/corpus.py
  gamechangerml/src/utilities/utils.py
  gamechangerml/train/pipeline.py
Labels: v1.4.0

#103 Task/UOT-132217 - more changes to finetuning data
  gamechangerml/api/fastapi/routers/controls.py
  gamechangerml/api/tests/api_tests.py
  gamechangerml/configs/config.py
  gamechangerml/data/test_data/MatamoFeedback_TEST.csv
  gamechangerml/data/test_data/SearchPDFMapping_TEST.csv
  gamechangerml/data/test_data/test_validation/any/intelligent_search_data.json
  gamechangerml/data/test_data/test_validation/any/intelligent_search_metadata.json
  gamechangerml/data/test_data/test_validation/gold/intelligent_search_data.json
  gamechangerml/data/test_data/test_validation/gold/intelligent_search_metadata.json
  gamechangerml/data/test_data/test_validation/silver/intelligent_search_data.json
  gamechangerml/data/test_data/test_validation/silver/intelligent_search_metadata.json
  gamechangerml/scripts/make_test_corpus.py
  gamechangerml/scripts/make_training_data.py
  gamechangerml/scripts/run_evaluation.py
  gamechangerml/scripts/update_eval_data.py
  gamechangerml/src/model_testing/evaluation.py
  gamechangerml/src/model_testing/query_es.py
  gamechangerml/src/model_testing/train_tests.py
  gamechangerml/src/model_testing/validation_data.py
  gamechangerml/src/search/sent_transformer/finetune.py
  gamechangerml/src/search/sent_transformer/model.py
  gamechangerml/src/text_handling/corpus.py
  gamechangerml/src/utilities/es_utils.py
  gamechangerml/src/utilities/test_utils.py
  gamechangerml/src/utilities/text_utils.py
  gamechangerml/train/pipeline.py
Labels: v1.4.0

#110 Task/uot 136030
  gamechangerml/api/fastapi/model_loader.py
  gamechangerml/api/fastapi/routers/controls.py
  gamechangerml/api/fastapi/routers/startup.py
  gamechangerml/api/fastapi/settings.py
  gamechangerml/api/fastapi/version.py
  gamechangerml/configs/config.py
  setup.py
Labels: v1.5.0

#109 Task/uot 137215
  gamechangerml/api/fastapi/routers/controls.py
  gamechangerml/train/pipeline.py
Labels: v1.5.0
