Repository dod-advana/gamechanger-ml, pull requests merged in 2022-01, with the labels that each got.

#78 Hotfix/evals upload
  gamechangerml/api/fastapi/routers/controls.py
  gamechangerml/src/model_testing/evaluation.py
  gamechangerml/src/search/sent_transformer/model.py
  gamechangerml/src/utilities/utils.py
  gamechangerml/train/pipeline.py
Labels: bug, release v1.1.0

#81 Task/uot 128452
  gamechangerml/data/ltr/featmap.txt
  gamechangerml/src/search/ranking/ltr.py
Labels: bug, enhancement

#82 Task/uot 123566
  gamechangerml/api/.env
  gamechangerml/api/fastapi/routers/startup.py
  gamechangerml/setup_env.sh
  gamechangerml/src/model_testing/validation_data.py
  gamechangerml/src/search/ranking/ltr.py
  gamechangerml/src/utilities/es_search_utils.py
  gamechangerml/src/utilities/es_utils.py
  gamechangerml/src/utilities/gc_web_api.py
  gamechangerml/train/pipeline.py
  setup.py
Labels: enhancement, v1.2.0

#77 Task/added script to pull transformers and upload to s3
  gamechangerml/api/fastapi/routers/controls.py
  gamechangerml/models/.gitignore
  gamechangerml/scripts/create_transformers_repo.sh
  gamechangerml/src/utilities/utils.py
Labels: enhancement, v1.2.0

#80 Feature/uot 125706 topics training api
  gamechangerml/__init__.py
  gamechangerml/api/fastapi/model_loader.py
  gamechangerml/api/fastapi/routers/controls.py
  gamechangerml/api/fastapi/routers/search.py
  gamechangerml/api/fastapi/routers/startup.py
  gamechangerml/api/fastapi/settings.py
  gamechangerml/api/utils/logger.py
  gamechangerml/api/utils/pathselect.py
  gamechangerml/api/utils/processmanager.py
  gamechangerml/api/utils/status_updater.py
  gamechangerml/configs/config.py
  gamechangerml/src/featurization/summary.py
  gamechangerml/src/featurization/topic_modeling.py
  gamechangerml/train/pipeline.py
  gamechangerml/train/scripts/README.md
  gamechangerml/train/scripts/__main__.py
  gamechangerml/train/scripts/cli.py
  lock.requirements.txt
  requirements.txt
Labels: enhancement, v1.2.0

#84 Feature/uot 126869 - recommend similar docs
  gamechangerml/api/fastapi/model_loader.py
  gamechangerml/api/fastapi/routers/search.py
  gamechangerml/api/fastapi/routers/startup.py
  gamechangerml/api/tests/api_tests.py
  gamechangerml/api/tests/test_examples.py
  gamechangerml/src/recommender/__init__.py
  gamechangerml/src/recommender/recommend.py
Labels: enhancement, v1.2.0

#85 Feature/UOT-125305
  gamechangerml/api/fastapi/routers/controls.py
  gamechangerml/api/utils/processmanager.py
  gamechangerml/scripts/create_transformers_repo.sh
  gamechangerml/src/utilities/utils.py
Labels: enhancement, v1.2.0

#86 fixing pip install for faiss
  setup.py
Labels: bug, v1.2.0
