Repository dod-advana/gamechanger-ml, pull requests merged in 2022-02, with the labels that each got.

#87 Feature/ UOT-129189
  .gitignore
  gamechangerml/api/docker-compose.yml
  gamechangerml/api/utils/processmanager.py
Labels: enhancement, v1.2.0

#91 [UOT-130905]
  gamechangerml/api/fastapi/routers/search.py
  gamechangerml/api/utils/pathselect.py
  gamechangerml/setup_env.sh
Labels: v1.2.0, jbook

#90 Feature/UOT-130237
  gamechangerml/api/fastapi/routers/controls.py
  gamechangerml/api/utils/processmanager.py
  gamechangerml/api/utils/threaddriver.py
Labels: enhancement, v1.2.0

#95 advana-release 1.2
  gamechangerml/scripts/download_dependencies.sh
  gamechangerml/src/recommender/recommend.py
Labels: v1.2.0

#98 feature/UOT-130865
  gamechangerml/api/.env
  gamechangerml/api/fastapi/routers/search.py
  gamechangerml/api/fastapi/settings.py
  gamechangerml/setup_env.sh
  gamechangerml/src/utilities/gc_web_api.py
Labels: v1.3.0

#96 Hotfix/uot 132724
  gamechangerml/api/fastapi/routers/controls.py
  gamechangerml/api/fastapi/version.py
  gamechangerml/api/utils/processmanager.py
  gamechangerml/configs/config.py
  gamechangerml/src/search/ranking/ltr.py
  gamechangerml/train/pipeline.py
  setup.py
Labels: v1.3.0

#99 Task/uot 131487 - Improves ML API for training qexp topics and others in ml dash
  gamechangerml/api/fastapi/model_loader.py
  gamechangerml/api/fastapi/routers/controls.py
  gamechangerml/api/fastapi/routers/search.py
  gamechangerml/api/tests/api_tests.py
  gamechangerml/api/utils/pathselect.py
  gamechangerml/configs/config.py
  gamechangerml/models/topic_models/__init__.py
  gamechangerml/models/topic_models/tfidf.py
  gamechangerml/setup_env.sh
  gamechangerml/src/featurization/word_sim.py
  gamechangerml/src/model_testing/validation_data.py
  gamechangerml/src/search/query_expansion/README.md
  gamechangerml/src/search/query_expansion/build_ann_cli/build_qe_model.py
  gamechangerml/src/search/sent_transformer/finetune.py
  gamechangerml/src/utilities/spacy_model.py
  gamechangerml/train/pipeline.py
Labels: v1.3.0
