Repository dod-advana/gamechanger-ml, pull requests merged in 2022-04, with the labels that each got.

#113 feature/UOT-139890
  gamechangerml/api/fastapi/routers/controls.py
  gamechangerml/data/user_data/UserAggregations.json
  gamechangerml/src/search/ranking/ltr.py
  gamechangerml/src/utilities/gc_web_api.py
Labels: enhancement, v1.6.0

#114 task/UOT-139858 - filtering bad paragraphs from sent index
  gamechangerml/api/tests/api_tests.py
  gamechangerml/api/tests/test_examples.py
  gamechangerml/src/text_handling/corpus.py
  gamechangerml/src/utilities/text_utils.py
Labels: enhancement, v1.6.0

#115 ability to recieve data from the frontend with the user aggregations
  gamechangerml/api/fastapi/routers/controls.py
  gamechangerml/data/user_data/UserAggregations.json
  gamechangerml/src/utilities/utils.py
Labels: v1.6.0

#117 add packages to allow tests to run
  gamechangerml/api/tests/requirements.txt
Labels: v1.7.0
